# Generated by Django 5.2.5 on 2025-08-12 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_booking_unique_together_booking_status_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='bookingseat',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'event', 'created_at')},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='raw_response',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('event', 'row_label', 'seat_number')},
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='row_label',
            field=models.CharField(default='A', max_length=4),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookingseat',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seat', to='events.seat'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='events.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='khalti', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Premium', 'Premium'), ('Standard', 'Standard')], default='Standard', max_length=10),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='number',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
    ]
