# Generated by Django 5.2.5 on 2025-08-14 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_seat_options_alter_bookingseat_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
    ]
